/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PersonsIndexRouteImport } from './routes/persons/index'
import { Route as PersonsIdRouteImport } from './routes/persons/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonsIndexRoute = PersonsIndexRouteImport.update({
  id: '/persons/',
  path: '/persons/',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonsIdRoute = PersonsIdRouteImport.update({
  id: '/persons/$id',
  path: '/persons/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/persons/$id': typeof PersonsIdRoute
  '/persons': typeof PersonsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/persons/$id': typeof PersonsIdRoute
  '/persons': typeof PersonsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/persons/$id': typeof PersonsIdRoute
  '/persons/': typeof PersonsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/persons/$id' | '/persons'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/persons/$id' | '/persons'
  id: '__root__' | '/' | '/persons/$id' | '/persons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PersonsIdRoute: typeof PersonsIdRoute
  PersonsIndexRoute: typeof PersonsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persons/': {
      id: '/persons/'
      path: '/persons'
      fullPath: '/persons'
      preLoaderRoute: typeof PersonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persons/$id': {
      id: '/persons/$id'
      path: '/persons/$id'
      fullPath: '/persons/$id'
      preLoaderRoute: typeof PersonsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PersonsIdRoute: PersonsIdRoute,
  PersonsIndexRoute: PersonsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
